# Generated by Django 5.0.4 on 2024-05-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notwhale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='password',
            field=models.CharField(default='', max_length=30, verbose_name='Пароль'),
        ),
    ]
